### ISSUE TITLE
Bump for v1.20.0 release

### ISSUE THREAD

**Issue by olivia-fox** [flathub/im.fluffychat.Fluffychat#116]
Hai! The @flathubbot did [correctly update this repo for the v1.20.0 release](https://github.com/flathub/im.fluffychat.Fluffychat/pull/115), but the [published version on flathub remains v1.19.2](https://flathub.org/apps/im.fluffychat.Fluffychat). Does something need to be manually done to sync up this repo and what's on flathub?

**Comment by krille-chan** [comment]
I've now idea. I thought this was automated now...

**Comment by krille-chan** [comment]
I tried a manual build now and published it. let's see if this works

**Comment by olivia-fox** [comment]
It did work, thank you! :3
