### ISSUE TITLE
Hi brothers

### ISSUE THREAD

**Issue by hotlittlewhitedog** [flathub/im.fluffychat.Fluffychat#21]
It's not a issue :)

I saw your recent update on flathub and would like to know if it was easy to publish for linux (flathub, snapcraft) a flutter app? (I also have a flutter app for IOS, Android, recently prepared for MACOS). So why not linux as I'm a linux user for years and it can touch a lot of distributions. 

Rem: it seems you are the only flutter app on flathub

Good continuation ++

**Comment by Raatty** [comment]
basically the flutter app gets built for Linux in gitlab ci then to create the flatpak version it just downloads the prebuilt app from gitlab to avoid trying to set up a proper flutter build system inside flatpak.

**Comment by krillefear** [comment]
Sorry for closing as this is not an issue.

Probably @kate-shine can tell you more :-) You can reach us on #fluffychat:matrix.org or on Reddit r/fluffychat for questions
