### ISSUE TITLE
HowTo jitsi sound beep call long an loud

### ISSUE THREAD

**Issue by sl5net** [flathub/im.fluffychat.Fluffychat#3]
yesterday we tried fluffychat. video/auto-call. this little short **jitsi sound beep**. nobody hears it. unusable. any way to make that call long an loud? we are temporarily switching to threema.
best is maybe "Slack - Incoming call sound" (audio config in fluffy). but its still very very short.

**Comment by ChristianPauly** [comment]
I dont know what you mean. Sorry. There is no Jitsi sound beep and no video/audio-call feature in the app, just a way to auto generate a jitsi url which is then opened. Also please open issues on the project page at GitLab. This is regarding to the Flatpak version.

**Comment by sl5net** [comment]
if we use fluffychat and try to call us jitsi is used. jitsi is not ringing like a typical phone call. right? means we dont hear it long enough. compare this please with element.io is not using jitsi for the 1to1 call. its very loud.
but element client is for some people to difficult. now you understand?

**Comment by ChristianPauly** [comment]
Yes, this is a duplication of: https://gitlab.com/famedly/fluffychat/-/issues/235 Thats why (like I have already said) Please! Open! Issues! On! Gitlab! Not! Here!
