### ISSUE TITLE
Failed to start Flutter renderer on PinePhone

### ISSUE THREAD

**Issue by Torbuntu** [flathub/im.fluffychat.Fluffychat#4]
Hardware: PinePhone beta edition (aarch64)
Operating System: Community fedora build (https://github.com/nikhiljha/pp-fedora-sdsetup)

When I try to launch FluffyChat I just get a blank window, and a warning in the terminal saying "Failed to start Flutter renderer: Unable to create a GL context"

**Comment by ChristianPauly** [comment]
Should be fixed now :)
