### ISSUE TITLE
Colour inversion if you launch Flatpak Fluffychat from the desktop file

### ISSUE THREAD

**Issue by Baggypants** [flathub/im.fluffychat.Fluffychat#67]
If you launch fluffychat using the desktop file the colours are iinverted

```
Fluffychat                                 im.fluffychat.Fluffychat                                1.6.3            stable         flathub     system
```

removing `GDK_gl=gles` seems to fix it.

**Comment by rdrms** [comment]
Can confirm this issue exists and the fix does work.

My specs:
Fedora Silverblue 36
Intel i7 3770 CPU + AMD RX570 GPU

**Comment by Raatty** [comment]
It's not as simple as just removing it for everyone it is required on some arm devices, I'll find a fix later but for now enjoy that it launches

**Comment by krille-chan** [comment]
Should be fixed now
