### ISSUE TITLE
Window Border Theme Not Taken From System

### ISSUE THREAD

**Issue by zicklag** [flathub/im.fluffychat.Fluffychat#7]
Hey there, just installed this app and noticed that the window theme was not copied from my system theme:

**Not right:**

![image](https://user-images.githubusercontent.com/25393315/126243895-6d7e0fa8-7059-4b11-9db0-2ac130fd0930.png)

**Right:**

![image](https://user-images.githubusercontent.com/25393315/126243933-3ad3f6cc-93ab-4e93-bac6-64cb1a1aaa4a.png)

I'm not sure what's necessary to setup flatpaks to read the system theme, but I've noticed that, in general, some do and some don't. It would be nice if fluffychat would.

**Comment by zicklag** [comment]
I know I've used other flutter apps before with the custom window decorations such as [nativeshell](https://github.com/nativeshell/nativeshell) examples and other Flutter desktop examples that I compiled myself.

It's something specific to the way flatpaks handle loading the system themes.

**Comment by vchernin** [comment]
Do other Flatpak apps reflect your theme correctly?

**Comment by zicklag** [comment]
Yes, but not all of them. There's some flatpak configuration that must be setup to make it pull in the system theme. I think it has to mount the themes folders from the host OS or something, but I haven't looked into the specific steps.

**Comment by vchernin** [comment]
Well your application/GTK theme should work automatically if your theme is available as a Flatpak on Flathub. However if it's not, you can workaround it by giving the Flatpak permission to read your themes folder. You could also try [Pakitheme](https://github.com/refi64/pakitheme) to package your theme as a Flatpak for you.

**Comment by zicklag** [comment]
That's interesting. :thinking: 

I use the Blender flatpak and it is able to read my theme, but I don't know how it does it. :man_shrugging:

**Comment by vchernin** [comment]
Blender Flatpak has [access](https://github.com/flathub/org.blender.Blender/blob/235c3fb03e0b25a691392ab7d0fedcc224a27ee0/org.blender.Blender.json#L13) to `"--filesystem=host"` which almost certainly covers themes. But that's a big workaround, themes can work in Flatpak without giving unnecessary filesystem permissions.

**Comment by zicklag** [comment]
I actually just tested disabling `--filesystem=host` using the Flatseal app for Blender, and verified that the theme _still_ works. Also I tested that flatpak was indeed blocking Blender's access to files it used to have access on the filesystem, such as the blends in my recent history, so that proves that disabling the setting was reducing access.

**Comment by zicklag** [comment]
Other apps that work include:

- Glade
- Inkscape
- Godot
- Tiled
- And some more I think

Not all of them theme the application widgets, such as with Tiled, but it at least has the window border themed correctly.

**Comment by vchernin** [comment]
Can you try giving filesystem=host to FluffyChat and see what happens?

**Comment by zicklag** [comment]
Ah, yes, enabling that does make the theme work with FluffyChat.

Also, all those apps I listed as working above also have `filesystem=host`, so that's why those work.

So we just have to figure out how Blender manages to get the theme without having `filesystem=host`

**Comment by vchernin** [comment]
Blender Flatpak likely just cached it somewhere since it had access before.

I recommend running `flatpak remote-ls flathub | grep org.gtk.Gtk3theme` to see if your theme exists at all on Flathub. If it doesn’t please request your theme author submit the theme to Flathub.

**Comment by zicklag** [comment]
> Blender Flatpak likely just cached it somewhere since it had access before.

I doubt it, because if I toggle that setting on and off with FluffyChat, it will switch the theme on and off as I restart the application, but that doesn't happen with Blender.

Still, I think it's reasonable to close this for now and if I ever discover what's going on with Blender I'll open a PR. Thanks!
