### ISSUE TITLE
Clicking links doesn't appear to work

### ISSUE THREAD

**Issue by edwargix** [flathub/im.fluffychat.Fluffychat#79]
Clicking links in Fluffychat doesn't seem to work.  The only way I can open a link is by copying the message with the link, pasting the content somewhere else (e.g. a text editor) and then copying/clicking the link from there.  This is pretty cumbersome because ofttimes links are in messages with other text, and you can only copy the message in full (unless I'm missing something?).

My system:

- [Sway](https://swaywm.org) version 1.8 (wlroots version 0.16.2) on Arch Linux
- Fluffychat version: 1.8.0 (stable)
- Flatpak version: 1.15.2
- xdg-desktop-portal version: 1.16.0
- desktop portal backends installed: xdg-desktop-portal-wlr
- xdg-desktop-portal-wlr version: 0.6.0

When I run Fluffychat with `flatpak run im.fluffychat.Fluffychat`, the following gets logged when I try to click on a link, so the problem might be with upstream rather than the flatpak pkg:

<details>

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      _isPressed.<anonymous closure> (package:keyboard_shortcuts/keyboard_shortcuts.dart:51)
#1      WhereIterator.moveNext (dart:_internal/iterable.dart:439)
#2      _isPressed (package:keyboard_shortcuts/keyboard_shortcuts.dart:55)
#3      _KeyBoardShortcuts.listener (package:keyboard_shortcuts/keyboard_shortcuts.dart:135)
#4      RawKeyboard.handleRawKeyEvent (package:flutter/src/services/raw_keyboard.dart:692)
#5      KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:878)
#6      BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:197)
#7      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:387)
#8      _invoke2 (dart:ui/hooks.dart:186)
#9      _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42)
#10     _Channel.push (dart:ui/channel_buffers.dart:132)
#11     ChannelBuffers.push (dart:ui/channel_buffers.dart:329)
#12     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:599)
#13     _dispatchPlatformMessage (dart:ui/hooks.dart:89)
```

</details>

**Comment by edwargix** [comment]
https://gitlab.com/famedly/fluffychat/-/issues/1045#note_1275429799

**Comment by q234rty** [comment]
The wlroots portal does not implement the required portal backend for link opening. You need xdg-desktop-portal-gtk. If that breaks screensharing please add `exec dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP=sway` to your sway config.

**Comment by edwargix** [comment]
> The wlroots portal does not implement the required portal backend for link opening.

Got it, thanks.  Do you happen to know what the ID for that functionality is?  (I'm not very familiar with desktop portals yet)
